[bar.default]
border_width = 2.0
center = ["active_window"]
end = [
    "media",
    "tray",
    "notifications",
    "network",
    "bluetooth",
    "volume",
    "brightness",
    "battery",
    "session",
]
margin_edge = 5
margin_ends = 5
start = ["workspaces", "spacer_2", "clock"]
thickness = 32

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "caffeine"

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "power_profile"

[[control_center.shortcuts]]
type = "dark_mode"

[desktop_widgets]
schema_version = 1
widget_order = []

[desktop_widgets.grid]
cell_size = 16
major_interval = 4
visible = true

[desktop_widgets.widget]

[shell]
polkit_agent = true
settings_show_advanced = true
telemetry_enabled = true

[shell.panel]
launcher_compact = true
open_near_click_control_center = true
open_near_click_session = true
session_placement = "floating"

[[shell.session.actions]]
action = "lock"
enabled = true
shortcut = "l"
variant = "default"

[[shell.session.actions]]
action = "logout"
enabled = true
shortcut = "u"
variant = "default"

[[shell.session.actions]]
action = "lock_and_suspend"
enabled = true
glyph = "player-pause"
shortcut = "s"
variant = "default"

[[shell.session.actions]]
action = "reboot"
enabled = true
shortcut = "r"
variant = "default"

[[shell.session.actions]]
action = "shutdown"
enabled = true
shortcut = "p"
variant = "destructive"

[theme.templates]
builtin_ids = ["alacritty", "gtk3", "gtk4", "kcolorscheme", "niri", "qt"]
community_ids = ["pywalfox", "obsidian", "vscode"]

[weather]
auto_locate = true

[widget.active_window]
max_length = 512

[widget.clock]
format = "{:%a %d.%m.%Y\\n%H:%M}"
scale = 1.5

[widget.date]
format = ""

[widget.media]
hide_when_no_media = true
max_length = 100

[widget.network]
show_label = false

[widget.spacer_2]
capsule = true
length = 15
type = "spacer"
